# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieSearchSwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieSearchSwiftUI
  pod 'Cara', git: 'https://github.com/icapps/ios-cara.git', commit: '79057213237f872a317221f4922f1a0fef619ad4'
end
